spring:
  application:
    name: demo


  ai:

    dashscope:
      api-key: sk-a7db25916f734fb180b6a0dec7d7eb60   # 建议用环境变量
      chat:
        options:
          model: qwen-turbo            # 也可用 qwen-turbo / qwen-long 等
          max-tokens: 1024

    openai:
      enable: false
      api-key: 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
      chat:
        options:
          model: gpt-3.5-turbo

    ollama:
      enable: false


server:
  port: 8080